credits_text =
"UNIVERSIDADE FEDERAL DO PARANÁ\n\n" +
"GABRIEL ANTONIO VEIGA\n" +
"JOÃO PEDRO QUEIROZ DEGER\n" +
"LEONARDO DOS SANTOS CORREIA\n" +
"URIEL DUARTE DE OLIVEIRA\n\n\n" +
"VILLE DES VERBES 2.0:\n" +
"UMA ABORDAGEM INTERATIVA PARA O\n" +
"APRENDIZADO DA CONJUGAÇÃO VERBAL EM FRANCÊS\n\n\n" +
"CURITIBA\n" +
"2025";

hover_voltar = false;